### ISSUE TITLE
White space in the widescreen

### ISSUE THREAD

**Issue by Lahphim** [akoliyot/nimbl3-dashboard#25]
I faced this issues when I opened with the widescreen.
It shows the white space on the right-hand side.
I'm not sure what's the root cause of this issues.
Could you please take care with this one for me? :)

![screen shot 2561-06-27 at 10 24 43](https://user-images.githubusercontent.com/749672/41951399-03b75992-79f5-11e8-8eec-9f3d3e55b2a3.png)

**Comment by akoliyot** [comment]
@Lahphim Does the layout always need to be full width? Or should there be a maximum width? The white space is there since the main content doesn't actually need the whole width. 

To fix this, I could: 
1. Set the background of the body to the same grey color (so you don't see the white anymore)
2. Set the <main> to always use fill width, but I think that would make the controls really wide.

**Comment by akoliyot** [comment]
If the background colour fix is okay, I already made the changes and merged to master. But if you want me to do the other one, let me know please :)

**Comment by Lahphim** [comment]
@akoliyot In my opinion, make it full-width content it looks ok.
I think we just only fill the background color seems weird for me because our contents are left justified, if our contents are center, change the background color might be ok with this decision.
I try to fix with this code.
What do you think?
```
main {
   width: 100%;
}
```

**Comment by akoliyot** [comment]
Yeah, the content does look a little weird when left aligned like that on a large screen. 

I'm not sure if center aligning the (main) content would be any better, because then on a very wide screen we'd have the sidebar on the far left and the content with lots of spaces on its left and right. 

So I think I agree with giving the main area 100% width.

**Comment by akoliyot** [comment]
@Lahphim I updated the width for the content – it's on master. Can you please check?

**Comment by akoliyot** [comment]
@Lahphim I'll wait for you to respond before closing the issue.

**Comment by Lahphim** [comment]
Fixed https://github.com/akoliyot/nimbl3-dashboard/commit/63646618fcd80e992e7005fadbe3e1a0fa1fdae2
